x-3dframe: &3dframe-defaults
    image: ghcr.io/arroyodev-llc/threedframe:latest
    tty: true
    privileged: true
    init: true
    build: &3dframe-build
        context: .
        target: workspace
        args:
            BLENDER_MAJOR: 3.2
            BLENDER_VERSION: 3.2.1
            BLENDER_ARCH: linux-x64
    environment:
        DISPLAY: $DISPLAY
        WAYLAND_DISPLAY: $WAYLAND_DISPLAY
        TERM: xterm-256color
        COLORTERM: truecolor
        3DFRAME_RENDERS_DIR: /data/renders
        LD_PRELOAD: /usr/lib/x86_64-linux-gnu/libGL.so
    devices:
        - /dev/dri:/dev/dri
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        - ./threedframe:/app/threedframe
        - ./tests:/app/tests
        - ./data:/data/models
        - ./renders:/data/renders
        - ./.direnv/ipython:/data/.ipython
        - ./openscad.conf:/data/.config/OpenSCAD/OpenSCAD.conf

x-3dframe-util: &3dframe-util
    <<: *3dframe-defaults
    profiles:
        - util

x-3dframe-mcg: &3dframe-mcg
    <<: *3dframe-defaults
    image: ghcr.io/arroyodev-llc/threedframe:mcg
    build:
        <<: *3dframe-build
        args:
            BLENDER_MAJOR: 3.2
            BLENDER_VERSION: 3.2.1
            BLENDER_ARCH: linux-x64
            OPENSCAD_REPO: "https://github.com/parvit/openscad.git"
            OPENSCAD_REV: "feature_multicore_geometry"


services:
    3dframe:
        <<: *3dframe-defaults

    3dframe-mcg:
        <<: *3dframe-mcg
        entrypoint: ["/docker-entrypoint.sh"]
        command: ["sleep", "21600"]

    shell:
        <<: *3dframe-util
        entrypoint: ["/docker-entrypoint.sh"]
        command: ["bash"]

    openscad:
        <<: *3dframe-util
        entrypoint: ["/docker-entrypoint.sh"]
        command: ["openscad"]

    open3d:
        <<: *3dframe-util
        entrypoint: ["/docker-entrypoint.sh", "open3d"]

    test:
        <<: *3dframe-util
        image: ghcr.io/arroyodev-llc/threedframe:test
        build:
            <<: *3dframe-build
            target: test-runner
