# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path

readme = ""
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, "README.rst")
if os.path.exists(readme_path):
    with open(readme_path, "rb") as stream:
        readme = stream.read().decode("utf8")


setup(
    long_description=readme,
    name="threedframe",
    version="0.0.0",
    description="Generate printable joints to create a real puzzle from any 3d model.",
    python_requires="==3.*,>=3.7.0",
    project_urls={
        "homepage": "https://github.com/BradenM/threedframe",
        "repository": "https://github.com/BradenM/threedframe",
    },
    author="Braden Mars",
    author_email="bradenmars@bradenmars.me",
    license="MIT license",
    classifiers=[
        "Natural Language :: English",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.9",
        "License :: OSI Approved :: MIT License",
    ],
    entry_points={"console_scripts": ["3dframe = threedframe.cli:main"]},
    packages=["threedframe", "threedframe.lib.MCAD"],
    package_dir={"": "."},
    package_data={
        "threedframe": [
            "lib/dotSCAD/*.md",
            "lib/dotSCAD/*.svg",
            "lib/dotSCAD/*.yml",
            "lib/dotSCAD/docs/*.md",
            "lib/dotSCAD/docs/images/*.JPG",
            "lib/dotSCAD/examples/*.md",
            "lib/dotSCAD/examples/*.scad",
            "lib/dotSCAD/examples/floor_stand/*.scad",
            "lib/dotSCAD/examples/hollow_out/*.scad",
            "lib/dotSCAD/examples/images/*.JPG",
            "lib/dotSCAD/examples/maze/*.scad",
            "lib/dotSCAD/examples/soccer_polyhedron/*.scad",
            "lib/dotSCAD/examples/taiwan/*.scad",
            "lib/dotSCAD/examples/tiles/*.scad",
            "lib/dotSCAD/examples/triangle2square/*.scad",
            "lib/dotSCAD/examples/turtle/*.scad",
            "lib/dotSCAD/examples/voronoi/*.scad",
            "lib/dotSCAD/featured_img/*.JPG",
            "lib/dotSCAD/src/*.scad",
            "lib/dotSCAD/src/__comm__/*.scad",
            "lib/dotSCAD/src/_impl/*.scad",
            "lib/dotSCAD/src/experimental/*.md",
            "lib/dotSCAD/src/experimental/*.scad",
            "lib/dotSCAD/src/experimental/_impl/*.scad",
            "lib/dotSCAD/src/experimental/demo/*.scad",
            "lib/dotSCAD/src/matrix/*.scad",
            "lib/dotSCAD/src/matrix/_impl/*.scad",
            "lib/dotSCAD/src/maze/*.scad",
            "lib/dotSCAD/src/maze/_impl/*.scad",
            "lib/dotSCAD/src/noise/*.scad",
            "lib/dotSCAD/src/noise/_impl/*.scad",
            "lib/dotSCAD/src/part/*.scad",
            "lib/dotSCAD/src/pixel/*.scad",
            "lib/dotSCAD/src/pixel/_impl/*.scad",
            "lib/dotSCAD/src/ptf/*.scad",
            "lib/dotSCAD/src/ptf/_impl/*.scad",
            "lib/dotSCAD/src/surface/*.scad",
            "lib/dotSCAD/src/surface/_impl/*.scad",
            "lib/dotSCAD/src/turtle/*.scad",
            "lib/dotSCAD/src/turtle/_impl/*.scad",
            "lib/dotSCAD/src/util/*.scad",
            "lib/dotSCAD/src/util/_impl/*.scad",
            "lib/dotSCAD/src/voronoi/*.scad",
            "lib/dotSCAD/src/voronoi/_impl/*.scad",
            "lib/dotSCAD/src/voxel/*.scad",
            "lib/dotSCAD/src/voxel/_impl/*.scad",
            "lib/dotSCAD/test/*.scad",
            "lib/dotSCAD/test/matrix/*.scad",
            "lib/dotSCAD/test/util/*.scad",
            "lib/dotSCAD/test/voxel/*.scad",
        ],
        "threedframe.lib.MCAD": ["*.markdown", "*.scad", "*.txt", "bitmap/*.scad"],
    },
    install_requires=[
        "attrs==20.*,>=20.3.0",
        "click==7.*,>=7.1.2",
        "numpy==1.*,>=1.19.5",
        "pydantic==1.*,>=1.8.1",
        "rich==9.*,>=9.10.0",
        "solidpython==1.*,>=1.0.4",
        "sympy==1.*,>=1.7.1",
        "vg==1.*,>=1.9.0",
        "watchdog==1.*,>=1.0.2",
    ],
    extras_require={
        "dev": [
            "autoflake==1.*,>=1.4.0",
            "docformatter==1.*,>=1.4.0",
            "fake-bpy-module-2.91==20201216.*,>=20201216.0.0",
            "flake8==3.*,>=3.7.0",
            "ipython==7.*,>=7.22.0",
            "isort==5.*,>=5.7.0",
            "jedi<0.18.0",
            "mypy==0.*,>=0.800.0",
            "pdbpp==0.*,>=0.10.2",
            "pre-commit==2.*,>=2.10.0",
            "pytest==6.*,>=6.2.2",
            "pytest-cov==2.*,>=2.11.1",
            "pytest-mock==3.*,>=3.5.1",
            "pytest-sugar==0.*,>=0.9.4",
            "pytest-testmon==1.*,>=1.0.0",
            "pytest-watch==4.*,>=4.2.0",
            "pytest-xdist==1.*,>=1.30.0",
            "rope==0.*,>=0.18.0",
            "sh==1.*,>=1.14.1",
            "snapshottest==0.*,>=0.6.0",
        ],
        "docs": [
            "recommonmark==0.*,>=0.7.1",
            "sphinx==3.*,>=3.4.3",
            "sphinx-autodoc-typehints==1.*,>=1.11.1",
            "sphinx-rtd-theme==0.*,>=0.5.1",
        ],
    },
)
