
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')


setup(
    long_description=readme,
    name='threedframe',
    version='0.0.0',
    description='Generate printable joints to create a real puzzle from any 3d model.',
    python_requires='==3.*,>=3.9.0',
    project_urls={"homepage": "https://github.com/BradenM/threedframe", "repository": "https://github.com/BradenM/threedframe"},
    author='Braden Mars',
    author_email='bradenmars@bradenmars.me',
    license='MIT license',
    classifiers=['Natural Language :: English', 'License :: OSI Approved :: MIT License', 'Programming Language :: Python', 'Programming Language :: Python :: 3', 'Programming Language :: Python :: 3.9', 'License :: OSI Approved :: MIT License'],
    packages=['threedframe'],
    package_dir={"": "."},
    package_data={},
    install_requires=['click==7.*,>=7.1.2', 'rich==9.*,>=9.10.0', 'solidpython==1.*,>=1.0.4'],
    extras_require={"dev": ["autoflake==1.*,>=1.4.0", "docformatter==1.*,>=1.4.0", "flake8==3.*,>=3.7.0", "isort==5.*,>=5.7.0", "mypy==0.*,>=0.800.0", "pre-commit==2.*,>=2.10.0", "pytest==6.*,>=6.2.2", "pytest-cov==2.*,>=2.11.1", "pytest-mock==3.*,>=3.5.1", "pytest-sugar==0.*,>=0.9.4", "pytest-testmon==1.*,>=1.0.0", "pytest-watch==4.*,>=4.2.0", "pytest-xdist==1.*,>=1.30.0", "rope==0.*,>=0.18.0"], "docs": ["recommonmark==0.*,>=0.7.1", "sphinx==3.*,>=3.4.3", "sphinx-autodoc-typehints==1.*,>=1.11.1", "sphinx-rtd-theme==0.*,>=0.5.1"]},
)
