# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path

readme = ""
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, "README.rst")
if os.path.exists(readme_path):
    with open(readme_path, "rb") as stream:
        readme = stream.read().decode("utf8")


setup(
    long_description=readme,
    name="threedframe",
    version="0.0.0",
    description="Generate printable joints to create a real puzzle from any 3d model.",
    python_requires="==3.*,>=3.8.0",
    project_urls={
        "homepage": "https://github.com/BradenM/threedframe",
        "repository": "https://github.com/BradenM/threedframe",
    },
    author="Braden Mars",
    author_email="bradenmars@bradenmars.me",
    license="MIT license",
    classifiers=[
        "Natural Language :: English",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.9",
        "License :: OSI Approved :: MIT License",
    ],
    entry_points={"console_scripts": ["3dframe = threedframe.cli:app"]},
    packages=["threedframe", "threedframe.models", "threedframe.scad"],
    package_dir={"": "."},
    package_data={
        "threedframe": [
            "*.iml",
            "lib/BOSL2/*.md",
            "lib/BOSL2/*.scad",
            "lib/BOSL2/.github/*.json",
            "lib/BOSL2/.github/ISSUE_TEMPLATE/*.md",
            "lib/BOSL2/.github/workflows/*.yml",
            "lib/BOSL2/examples/*.scad",
            "lib/BOSL2/images/*.png",
            "lib/BOSL2/scripts/*.sh",
            "lib/BOSL2/tests/*.scad",
            "lib/BOSL2/tutorials/*.md",
        ]
    },
    install_requires=[
        "attrs==20.*,>=20.3.0",
        "loguru==0.*,>=0.5.3",
        "numpy==1.*,>=1.19.5",
        "ply==3.*,>=3.11.0",
        "psutil==5.*,>=5.8.0",
        "pydantic==1.*,>=1.8.1",
        "rich==9.*,>=9.10.0",
        "solidpython",
        "sympy==1.*,>=1.7.1",
        "typer[all]==0.*,>=0.3.2",
        "vg==1.*,>=1.9.0",
        "watchdog==1.*,>=1.0.2",
    ],
    dependency_links=["git+https://github.com/jeff-dh/SolidPython.git@exp_solid#egg=solidpython"],
    extras_require={
        "dev": [
            "argh==0.*,>=0.26.2",
            "autoflake==1.*,>=1.4.0",
            "codetiming==1.*,>=1.3.0",
            "devtools[pygments]==0.*,>=0.6.1",
            "docformatter==1.*,>=1.4.0",
            "fake-bpy-module-2.91==20201216.*,>=20201216.0.0",
            "flake8==3.*,>=3.7.0",
            "hypothesis[cli,codemods]==6.*,>=6.13.1",
            "ipython==7.*,>=7.22.0",
            "isort==5.*,>=5.7.0",
            "jedi<0.18.0",
            "mypy==0.*,>=0.800.0",
            "pdbpp==0.*,>=0.10.2",
            "pre-commit==2.*,>=2.10.0",
            "pytest==6.*,>=6.2.2",
            "pytest-cov==2.*,>=2.11.1",
            "pytest-mock==3.*,>=3.5.1",
            "pytest-sugar==0.*,>=0.9.4",
            "pytest-testmon==1.*,>=1.0.0",
            "pytest-watch==4.*,>=4.2.0",
            "pytest-xdist==1.*,>=1.30.0",
            "rope==0.*,>=0.18.0",
            "sh==1.*,>=1.14.1",
            "snapshottest==0.*,>=0.6.0",
        ],
        "docs": [
            "recommonmark==0.*,>=0.7.1",
            "sphinx==3.*,>=3.4.3",
            "sphinx-autodoc-typehints==1.*,>=1.11.1",
            "sphinx-rtd-theme==0.*,>=0.5.1",
        ],
    },
)
