name: 3DFrame

on:
    workflow_dispatch:
    push:
        branches:
            - master

jobs:
    build:
        name: Build Image
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  submodules: true

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to Registry
              uses: docker/login-action@v1
              if: github.event_name != 'pull_request'
              with:
                  registry: ghcr.io
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Set Environment
              run: |
                  IMG=threedframe
                  echo "IMG=${IMG}" >> $GITHUB_ENV
                  echo "IMAGE=$(echo ghcr.io/${{ github.repository_owner }}/${IMG} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
                  echo "BUILD_DATE=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
                  echo "GIT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
                  echo "GIT_REF=$(git symbolic-ref -q --short HEAD || git describe --tags --exact-match)" >> $GITHUB_ENV
                  echo "BUILD_VER=1.0.0-alpha.${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
                  echo "NUM_CORES=$(nproc)" >> $GITHUB_ENV

            - name: Build and Push
              uses: docker/build-push-action@v2
              if: github.event_name != 'pull_request'
              with:
                  context: .
                  file: ./Dockerfile
                  build-args: |
                      NUM_CORES=${{ env.NUM_CORES }}
                  labels: |
                      org.opencontainers.image.authors=${{ github.repository_owner }}
                      org.opencontainers.image.created=${{ env.BUILD_DATE }}
                      org.opencontainers.image.description=Created from commit ${{ env.GIT_SHA }} and ref ${{ env.GIT_REF }}
                      org.opencontainers.image.ref.name=${{ env.GIT_REF }}
                      org.opencontainers.image.revision=${{ github.sha }}
                      org.opencontainers.image.source=https://github.com/${{ github.repository }}
                      org.opencontainers.image.version=${{ env.BUILD_VER }}
                  tags: |
                      ${{ env.IMAGE }}:latest
                      ${{ env.IMAGE }}:${{ env.GIT_REF }}
                      ${{ env.IMAGE }}:${{ env.GIT_SHA }}
                      ${{ env.IMAGE }}:${{ env.BUILD_VER }}
                  push: true
                  secrets: |
                      GIT_AUTH_TOKEN=${{ secrets.DOCKER_PASSWORD }}

    render:
        name: Render Joints
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  submodules: true

            - name: Login to Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build
              run: docker run --rm --user 100 --entrypoint /app/threedframe/cli.py -v $(pwd):/app/ ghcr.io/arroyodev-llc/threedframe:latest generate data/cybersticks.json -v 1-10 --render -b parallel
